#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# Requirements:
# The redirection must be a “301 Moved Permanently”
# You answer file should be a Bash script containing commands to automatically configure a Ubuntu machine to respect above requirements
# Using what you did with 1-install_nginx_web_server, write 3-redirection so that it configures a brand new Ubuntu machine to the requirements asked in this task
apt-get update
apt-get install -y nginx
rm -rf /etc/nginx/html
mkdir /etc/nginx/html
rm -f /etc/nginx/html/index.html
touch /etc/nginx/html/index.html
echo "Hello World" > /etc/nginx/html/index.html
printf %s "server {
	root        /etc/nginx/html;
	index       index.html index.htm;
	listen      80 default_server;
	listen      [::]:80 default_server;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}
" > /etc/nginx/sites-available/default
service nginx restart
