#!/usr/bin/env bash
# displays bad luck for 4th, good luck for 8th, Best School for the others.

COUNTER=1
while [ $COUNTER -lt 11 ]
do
	if [ $COUNTER = 4 ]
	then
		echo "bad luck"
	elif [ $COUNTER = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	let COUNTER+=1
done
